### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by bryant-the-coder** [kwakzalver/duckytype.nvim#1]
Try adding a keybinding to quit it. Like `q` to quit. And when users finish typing, press `Enter` to quit is also another way

**Comment by kwakzalver** [comment]
It's a regular vim window, `:q` should quit it.
Seems a bit overkill to add another keybinding to do the exact same thing, if anyone else also thinks it should be done we'll just do it. :)

**Comment by bryant-the-coder** [comment]
Ok. Where or which website do you use to find all the keywords?

**Comment by bryant-the-coder** [comment]
> It's a regular vim window, `:q` should quit it. Seems a bit overkill to add another keybinding to do the exact same thing, if anyone else also thinks it should be done we'll just do it. :)

In order to do `:q`, users will have to leave insert mode :(

**Comment by kwakzalver** [comment]
I have made minor edits so the user goes into normal mode on finish.
Hitting the `Enter` key then allows for a quick new game, `:q` is not too far either.

The keywords I had laying around, if there are any missing for a particular programming language (or anything else that would be fun for people to type) feel free to make a new issue/pull request.

**Comment by bryant-the-coder** [comment]
Sure do. Will try it at once.

**Comment by bryant-the-coder** [comment]
![image](https://user-images.githubusercontent.com/92417638/164968849-d7394457-a2f5-47ca-a957-13b39f99df27.png)
dont mind that bg

**Comment by bryant-the-coder** [comment]
getting this error

**Comment by kwakzalver** [comment]
Nice catch! I fixed it just now. :smile:

**Comment by bryant-the-coder** [comment]
hey, is this normal? 

![image](https://user-images.githubusercontent.com/92417638/164978817-556e22d8-31ee-43ab-b4b8-f46876899879.png)
I have this as my config

but this is what it appears
![image](https://user-images.githubusercontent.com/92417638/164978879-56466bfc-b696-4887-baf5-75e0e1f7cf45.png)

**Comment by bryant-the-coder** [comment]
yes, it doesnt work.

**Comment by kwakzalver** [comment]
just for the github record, currently there aren't any issues anymore, right?

**Comment by bryant-the-coder** [comment]
yes for now :))
