### ISSUE TITLE
Plug Support

### ISSUE THREAD

**Issue by michalspano** [kwakzalver/duckytype.nvim#5]
### `Plug` (or other package manager) Support

Perhaps, adding support for a **plugin manager**, like `Plug`, could come in handy!

**Comment by kwakzalver** [comment]
Does it somehow not work for you?
I think the below snippet should work just fine with junegunn's vim-plug (https://github.com/junegunn/vim-plug)
```vim
Plug 'kwakzalver/duckytype.nvim'
```

**Comment by michalspano** [comment]
I see, that does, indeed, work as expected. I, however, could not find this instruction in the `readme.md`. I suppose that, for clarity, it could come in handy if it was added there, so, new uesers, like myself, will not be misled. :)
Closing the issue; thanks for getting back to it!
